model_name_or_path: Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
use_peft: True
load_in_4bit: True
output_dir: runs/qwen-2.5-3b-r1-guessing

dataset_id_or_path: 'guessing'
# Dataset arguments
dataset_name: 'guessing'
# Lora Arguments
# No LoRA is used here

# Training arguments

max_steps: 500
per_device_train_batch_size: 10
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1e-6 # 1.0e-6 as in the deepseek math paper 5-e7 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
lr_scheduler_type: cosine
warmup_ratio: 0.05
# GRPO specific parameters
beta: 0.001 # 0.04 as in the deepseek math paper 0.001 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
max_prompt_length: 256
max_completion_length: 1024
num_generations: 10
use_vllm: True
max_grad_norm: 1.0
log_completions: True
model_init_kwargs:
  use_cache: false
vllm_device: "cuda:0"
vllm_gpu_memory_utilization: 0.5
eval_strategy: steps  # 启用评估策略
eval_steps: 100              # 每 50 步进行一次评估
per_device_eval_batch_size: 20  # 设置评估时的 batch size
eval_accumulation_steps: 1     # 累积梯度步数（可选）
resume_from_checkpoint: True

# Logging arguments
logging_strategy: steps
logging_steps: 2
report_to:
- wandb
save_strategy: "steps"
save_steps: 25
seed: 42

# Hugging Face Hub 
push_to_hub: true
  # hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
hub_strategy: every_save